<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OR008_EditButton</name>
   <tag></tag>
   <elementGuidId>9e65ff6f-339f-4bcf-8ac7-2b4a71c754a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__layout&quot;]/section/section/main/div[2]/div/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td/a[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
